spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
  liquibase:
    change-log: "classpath:db/changelog/changelog-master.xml"

server:
  port: 8182
  servlet:
    context-path: /market-auth
jwt:
  secret: "1324nj3k545gbko3qnhk54jh6hk675lgjgkh54r6d85khgt45dhfg76fj4lee56785ghfgg0d8fj"
  lifetime: "3600000"




