server:
  port: 8180
spring:
  application:
    name: /gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8100"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8181
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8182
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
        - id: order-service
          uri: http://localhost:8183
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-order
            - JwtAuthFilter


jwt:
  secret: "1324nj3k545gbko3qnhk54jh6hk675lgjgkh54r6d85khgt45dhfg76fj4lee56785ghfgg0d8fj"

