server:
  port: 8183
  servlet:
    context-path: /market-order

integrations:
  auth-service:
    url: http://localhost:8182/market-auth/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
  product-service:
    url: http://localhost:8181/market-core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
  kafka:
    bootstrap-servers: "localhost:29092"
  liquibase:
    change-log: "classpath:db/changelog/changelog-master.xml"
logging:
  level:
    com.geekbrains.orderservice: debug
paypal:
  client-id: "AbFiLJi4qESYtT2B7ZPZv-Ys-v5B5HceiNVe0Y5tZTENvqSbZdaXVebrfA_JkW_Y8ia385kED9g2mIb5"
  client-secret: "EIeUIAdver4iwqpFZnpg9UPuiUvUM1Dfylu5UNyFvEwagsCs6E1W9qeF2Y7GVGc9rm0Mj7T5GBEaJveJ"


#  credentials for PayPal
#  email: sb-leivi20938092@personal.example.com
#  password: 3JWz.%1Q
#  phone: 4089368965
