server:
  port: 8183
  servlet:
    context-path: /market-cart

integrations:
  auth-service:
    url: http://localhost:8182/market-auth/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
  product-service:
    url: http://localhost:8181/market-core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"