server:
  port: 8181
  servlet:
    context-path: /market-core
spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
  liquibase:
    change-log: "classpath:db/changelog/changelog-master.xml"

gateway:
  path: "http://localhost:8180/core/"

directory: "${user.dir}\\Files\\"


